# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VivTxUG0WVh6QoNP-GDbx8nEhh0fz5H4
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
# %matplotlib inline
import missingno as msno

from google.colab import drive

drive.mount('/content/gdrive')

cd /content/gdrive/My Drive/Colab Notebooks/ML PRACTICAL/Logistic Regression/

columns = ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Class_labels'] 
df = pd.read_csv('Iris.csv', names=columns)
df.head()

df.columns

df.info()

df.describe()

df.describe().T

df.isnull().head(10)

df.isnull().sum()

d = msno.bar(df)

df.head()

feature_cols = ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Class_labels']
X = df[feature_cols]
y = df.Class_labels

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

df = df.replace(r'^\s*$', np.nan, regex=True)